{"message": "Debug uzenet", "timestamp": "2024-11-10T18:24:01.602609+01:00", "level": "DEBUG", "logger": "logging_4", "module": "logging_4", "function": "main", "line": 128, "thread_name": "MainThread"}
{"message": "Info uzenet", "timestamp": "2024-11-10T18:24:01.602609+01:00", "level": "INFO", "logger": "logging_4", "module": "logging_4", "function": "main", "line": 129, "thread_name": "MainThread"}
{"message": "Warning \u00fczenet", "timestamp": "2024-11-10T18:24:02.048949+01:00", "level": "WARNING", "logger": "logging_4", "module": "logging_4", "function": "main", "line": 130, "thread_name": "MainThread"}
{"message": "Error uzenet", "timestamp": "2024-11-10T18:24:02.099583+01:00", "level": "ERROR", "logger": "logging_4", "module": "logging_4", "function": "main", "line": 131, "thread_name": "MainThread"}
{"message": "Critical uzenet", "timestamp": "2024-11-10T18:24:02.164072+01:00", "level": "CRITICAL", "logger": "logging_4", "module": "logging_4", "function": "main", "line": 132, "thread_name": "MainThread"}
{"message": "Exception uzenet", "timestamp": "2024-11-10T18:24:02.182238+01:00", "exc_info": "Traceback (most recent call last):\n  File \"h:\\DADY\\rend\\konyvtarak\\2024\\241106_1319_python_logging\\python_logging\\logging_4.py\", line 134, in main\n    1 / 0\n    ~~^~~\nZeroDivisionError: division by zero", "level": "ERROR", "logger": "logging_4", "module": "logging_4", "function": "main", "line": 136, "thread_name": "MainThread"}
